### ISSUE TITLE
VSPipe problem

### ISSUE THREAD

**Issue by truefriend-cz** [DaGooseYT/EncodeGUI#8]
How i can fix this?
![image](https://user-images.githubusercontent.com/7845691/196028577-ace5fe24-5d2a-4dd0-a3fd-2093985c99b9.png)

GPU driver is latest - i have select Nvidia but in title bad show second GPU.

![image](https://user-images.githubusercontent.com/7845691/196028635-c5f7b5a3-3cb6-40b0-a26b-2f9058b80362.png)

`#================================================#
EncodeGUI process logs for job 11414516
Video encoding arguments: "U:\Downloads\P\EncodeGUI\vapoursynth\vspipe.exe" -c y4m "C:\Users\Administrator\AppData\Local\EncodeGUI\job-11414516\11414516.vpy" - | "U:\Downloads\P\EncodeGUI\ffmpeg\ffmpeg.exe" -y -i - -c:v libx264 -crf 22 -preset slow "C:\Users\Administrator\AppData\Local\Temp\11414516.mkv"
Audio encoding arguments: "U:\Downloads\P\EncodeGUI\ffmpeg\ffmpeg.exe" -y -i "C:\Users\Administrator\AppData\Local\Temp\11414516.mkv" -i "U:\Temp\VID_20220910_161404.mp4" -map 0:v -c:v copy -map 1:a -c:a copy -metadata:g encoding_tool="EncodeGUI v1.1.0d" "U:\Temp\VID_20220910_161404-egui.mp4"
#================================================#

ffmpeg version n5.1-1-g6d83c5f876-20220727 Copyright (c) 2000-2022 the FFmpeg developers
  built with gcc 12.1.0 (crosstool-NG 1.25.0.55_3defb7b)
  configuration: --prefix=/ffbuild/prefix --pkg-config-flags=--static --pkg-config=pkg-config --cross-prefix=x86_64-w64-mingw32- --arch=x86_64 --target-os=mingw32 --enable-gpl --enable-version3 --disable-debug --enable-shared --disable-static --disable-w32threads --enable-pthreads --enable-iconv --enable-libxml2 --enable-zlib --enable-libfreetype --enable-libfribidi --enable-gmp --enable-lzma --enable-fontconfig --enable-libvorbis --enable-opencl --disable-libpulse --enable-libvmaf --disable-libxcb --disable-xlib --enable-amf --enable-libaom --enable-libaribb24 --enable-avisynth --enable-libdav1d --enable-libdavs2 --disable-libfdk-aac --enable-ffnvcodec --enable-cuda-llvm --enable-frei0r --enable-libgme --enable-libass --enable-libbluray --enable-libjxl --enable-libmp3lame --enable-libopus --enable-librist --enable-libtheora --enable-libvpx --enable-libwebp --enable-lv2 --enable-libmfx --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopenmpt --enable-librav1e --enable-librubberband --enable-schannel --enable-sdl2 --enable-libsoxr --enable-libsrt --enable-libsvtav1 --enable-libtwolame --enable-libuavs3d --disable-libdrm --disable-vaapi --enable-libvidstab --enable-vulkan --enable-libshaderc --enable-libplacebo --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libzimg --enable-libzvbi --extra-cflags=-DLIBTWOLAME_STATIC --extra-cxxflags= --extra-ldflags=-pthread --extra-ldexeflags= --extra-libs=-lgomp --extra-version=20220727
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100

Script evaluation failed:
Python exception: Resize error: bad value: transfer_in_s

Traceback (most recent call last):
  File "src\cython\vapoursynth.pyx", line 2759, in vapoursynth._vpy_evaluate
  File "src\cython\vapoursynth.pyx", line 2760, in vapoursynth._vpy_evaluate
  File "C:\Users\Administrator\AppData\Local\EncodeGUI\job-11414516\11414516.vpy", line 15, in <module>
    clip = core.resize.Lanczos(clip, format=vs.RGBS, matrix_in_s="170m", transfer_in_s="170m", primaries_in_s="470bg")
  File "src\cython\vapoursynth.pyx", line 2507, in vapoursynth.Function.__call__
vapoursynth.Error: Resize error: bad value: transfer_in_s

pipe:: Invalid data found when processing input

#================================================#
End of logs
#================================================#
`

**Comment by DaGooseYT** [comment]
smtpe170m isn't supported by VapourSynth as an input color transfer. Enable `Color Space Converter` in Video > VapourSynth > Colors tabs and set the input output color spaces to the following:

Input: BT470bg/BT709/BT470bg
Output: BT709/BT709/BT709

Add a new job to the queue consisting of the above along with the other settings you have set.

**Comment by truefriend-cz** [comment]
Can you add this condition to the application so that it executes automatically?

And why is the Intel graphics card displayed in the tilte bar when I have an nVidia graphics card selected in the application? (including dual GPU settings (I have both graphics cards set to "1" which is nVidia)). My laptop contains two graphics cards (Intel "0" and nVidia "1").

**Comment by DaGooseYT** [comment]
A condition can't be made because it isn't safe for the color spaces to be automatically assumed (can cause visual glitches or washed out colors due to incorrect spaces, etc.). The best option is to wait for a VapourSynth update to support smpte170m as a color transfer.

As for the GPU in the title bar, it appears you are using a laptop which consists of an iGPU (Intel) and a dGPU (NVIDIA). In order for EncodeGUI to index the dGPU as GPU0, you must change the graphics settings for EncodeGUI in windows settings to use your dGPU instead of the defaulted iGPU. What GPU you select in any of the filters doesn't change the title bar. See the first accordion drop-down menu on https://encodegui.com/support.html for details.

**Comment by DaGooseYT** [comment]
Closing due to inactivity (assumed fixed).
